---

- hosts: all

  vars:
    pacmanrepo_source: .
    pacmanrepo_name: yourlabs
    pacmanrepo_destination: /home/arch/mirror/yourlabs

  roles:
  - role: jpic.pacmanrepo
    pacmanrepo_architecture: any

  - role: jpic.pacmanrepo
    pacmanrepo_architecture: x86_64

  - role: jpic.pacmanrepo
    pacmanrepo_architecture: i686
